[build]
    command = "pnpm run build || ( npm install pnpm && pnpm run build )"

# Skip Netlify's `npm install` command so that we can use our own `prebuild`
# script that runs pnpm
[build.environment]
    NPM_FLAGS="--prefix=/dev/null"
